// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACXkzBszAYjqtsdrQc5aa1jV-zpeueBlc',
    appId: '1:405011066245:web:a012abe62c2b1902faa8ec',
    messagingSenderId: '405011066245',
    projectId: 'btlck-63289',
    authDomain: 'btlck-63289.firebaseapp.com',
    storageBucket: 'btlck-63289.firebasestorage.app',
    measurementId: 'G-SFLB6HWNGY',
    databaseURL:
        'https://btlck-63289-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvejaadHl6kF8k-bY5hbeU_Aoklb8TziU',
    appId: '1:405011066245:android:7a474777ff7cd328faa8ec',
    messagingSenderId: '405011066245',
    projectId: 'btlck-63289',
    storageBucket: 'btlck-63289.firebasestorage.app',
    databaseURL:
        'https://btlck-63289-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm3zhR_D2hJAIXMKHVhSnxOmoboHGI43Q',
    appId: '1:405011066245:ios:f62a39234b1e0118faa8ec',
    messagingSenderId: '405011066245',
    projectId: 'btlck-63289',
    storageBucket: 'btlck-63289.firebasestorage.app',
    iosBundleId: 'com.example.btlCk',
    databaseURL:
        'https://btlck-63289-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm3zhR_D2hJAIXMKHVhSnxOmoboHGI43Q',
    appId: '1:405011066245:ios:f62a39234b1e0118faa8ec',
    messagingSenderId: '405011066245',
    projectId: 'btlck-63289',
    storageBucket: 'btlck-63289.firebasestorage.app',
    iosBundleId: 'com.example.btlCk',
    databaseURL:
        'https://btlck-63289-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACXkzBszAYjqtsdrQc5aa1jV-zpeueBlc',
    appId: '1:405011066245:web:f1e9a0208ab8464cfaa8ec',
    messagingSenderId: '405011066245',
    projectId: 'btlck-63289',
    authDomain: 'btlck-63289.firebaseapp.com',
    storageBucket: 'btlck-63289.firebasestorage.app',
    measurementId: 'G-VYEWRBTM0H',
    databaseURL:
        'https://btlck-63289-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
